CREATE TABLE Affiliated (ProjectID int(10) NOT NULL, SectionName varchar(30) NOT NULL, PRIMARY KEY (ProjectID, SectionName));
CREATE TABLE Choices (ProjectID int(10) NOT NULL, UserID int(10) NOT NULL, Weight int(1), PRIMARY KEY (ProjectID, UserID));
CREATE TABLE Expert (ID int(10) NOT NULL AUTO_INCREMENT, Name varchar(40) NOT NULL, FirstName varchar(40), Email varchar(50) NOT NULL, PhoneNumber int(11) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE ExpertPerProject (ExpertID int(10) NOT NULL, ProjectID int(10) NOT NULL, PRIMARY KEY (ExpertID, ProjectID));
CREATE TABLE Externe (ID int(10) NOT NULL AUTO_INCREMENT, Name varchar(40) NOT NULL, Email varchar(50) NOT NULL, PhoneNumber int(11), PRIMARY KEY (ID));
CREATE TABLE Externe_Project (ExterneID int(10) NOT NULL, ProjectID int(10) NOT NULL, PRIMARY KEY (ExterneID, ProjectID));
CREATE TABLE InCharge (ProjectID int(10) NOT NULL, UserID int(10) NOT NULL, PRIMARY KEY (ProjectID, UserID));
CREATE TABLE KeyWords (Word varchar(40) NOT NULL, PRIMARY KEY (Word));
CREATE TABLE KeyWordsByProject (KeyWordsWord varchar(40) NOT NULL, ProjectID int(10) NOT NULL, PRIMARY KEY (KeyWordsWord, ProjectID));
CREATE TABLE LinkAndRef (ID int(10) NOT NULL AUTO_INCREMENT, Link varchar(100) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE LinkAndRef_Project (LinkAndRefID int(10) NOT NULL, ProjectID int(10) NOT NULL, PRIMARY KEY (LinkAndRefID, ProjectID));
CREATE TABLE Project (ID int(10) NOT NULL AUTO_INCREMENT, Title varchar(100) NOT NULL, Description varchar(400), Abreviation varchar(40), State SET('Saisie', 'Validation', 'Valide', 'Concours', 'Attribue', 'Termine', 'Publie') DEFAULT 'Saisie' NOT NULL, NbrMaxStudent int(5), Year varchar(10), ClientName varchar(40), Language SET('Francais', 'Deutsch', 'English') DEFAULT 'Francais', `Public` tinyint(1) DEFAULT 0 NOT NULL, UserID_Owner int(10) NOT NULL, TypeName varchar(20), PRIMARY KEY (ID));
CREATE TABLE Section (Name varchar(30) NOT NULL, PRIMARY KEY (Name));
CREATE TABLE Type (Name varchar(20) NOT NULL, CreditECTS double NOT NULL, PRIMARY KEY (Name));
CREATE TABLE `User` (ID int(10) NOT NULL AUTO_INCREMENT, Name varchar(20) NOT NULL, FirstName varchar(40) NOT NULL, Email varchar(50) NOT NULL, Login varchar(40) NOT NULL, Role SET('Etudiant', 'Professeur', 'Responsable') DEFAULT 'Etudiant' NOT NULL, SectionName varchar(30), ProjectID_Assigned int(10), PRIMARY KEY (ID));
ALTER TABLE LinkAndRef_Project ADD CONSTRAINT FKLinkAndRef19375 FOREIGN KEY (ProjectID) REFERENCES Project (ID);
ALTER TABLE LinkAndRef_Project ADD CONSTRAINT FKLinkAndRef728566 FOREIGN KEY (LinkAndRefID) REFERENCES LinkAndRef (ID);
ALTER TABLE Project ADD CONSTRAINT FKProject522735 FOREIGN KEY (TypeName) REFERENCES Type (Name);
ALTER TABLE Externe_Project ADD CONSTRAINT FKExterne_Pr943403 FOREIGN KEY (ProjectID) REFERENCES Project (ID);
ALTER TABLE ExpertPerProject ADD CONSTRAINT FKExpertPerP600514 FOREIGN KEY (ProjectID) REFERENCES Project (ID);
ALTER TABLE KeyWordsByProject ADD CONSTRAINT FKKeyWordsBy679806 FOREIGN KEY (ProjectID) REFERENCES Project (ID);
ALTER TABLE Affiliated ADD CONSTRAINT FKAffiliated169936 FOREIGN KEY (ProjectID) REFERENCES Project (ID);
ALTER TABLE InCharge ADD CONSTRAINT FKInCharge976995 FOREIGN KEY (ProjectID) REFERENCES Project (ID);
ALTER TABLE Choices ADD CONSTRAINT FKChoices887491 FOREIGN KEY (ProjectID) REFERENCES Project (ID);
ALTER TABLE InCharge ADD CONSTRAINT FKInCharge948184 FOREIGN KEY (UserID) REFERENCES `User` (ID);
ALTER TABLE Choices ADD CONSTRAINT FKChoices858680 FOREIGN KEY (UserID) REFERENCES `User` (ID);
ALTER TABLE Affiliated ADD CONSTRAINT FKAffiliated185407 FOREIGN KEY (SectionName) REFERENCES Section (Name);
ALTER TABLE KeyWordsByProject ADD CONSTRAINT FKKeyWordsBy10970 FOREIGN KEY (KeyWordsWord) REFERENCES KeyWords (Word);
ALTER TABLE ExpertPerProject ADD CONSTRAINT FKExpertPerP933024 FOREIGN KEY (ExpertID) REFERENCES Expert (ID);
ALTER TABLE Externe_Project ADD CONSTRAINT FKExterne_Pr407613 FOREIGN KEY (ExterneID) REFERENCES Externe (ID);
ALTER TABLE `User` ADD CONSTRAINT Assigned FOREIGN KEY (ProjectID_Assigned) REFERENCES Project (ID);
ALTER TABLE Project ADD CONSTRAINT Owns FOREIGN KEY (UserID_Owner) REFERENCES `User` (ID);
ALTER TABLE `User` ADD CONSTRAINT Studies FOREIGN KEY (SectionName) REFERENCES Section (Name);
