INSERT INTO Section
    (Name)
VALUES
    ('Informatique'),
    ('Architecture'),
    ('Internet et communication'),
    ('Chimie'),
    ('Télécomunication');

INSERT INTO User
    (Name, FirstName, Email, Login, Role, SectionName)
VALUES
    ('Doudin', 'Yann', 'yann.doudin@edu.hefr.ch', 'yann.doudin', 'Responsable', 'Informatique'),
    ('Std1 ', 'Aeberhard Cédric', 'myname.std1@edu.hefr.ch', 'myname1.std', 'Etudiant', 'Informatique'),
    ('Std2 ', 'Alvarez David', 'myname.std2@edu.hefr.ch', 'myname2.std', 'Etudiant', 'Informatique'),
    ('Std3 ', 'Audriaz Patrick', 'myname.std3@edu.hefr.ch', 'myname3.std', 'Etudiant', 'Informatique'),
    ('Std4 ', 'Beffa Yann', 'myname.std4@edu.hefr.ch', 'myname4.std', 'Etudiant', 'Informatique'),
    ('Std5 ', 'Borgognon Julien', 'myname.std5@edu.hefr.ch', 'myname5.std', 'Etudiant', 'Informatique'),
    ('Std6 ', 'Bouteille Cédric', 'myname.std6@edu.hefr.ch', 'myname6.std', 'Etudiant', 'Informatique'),
    ('Std7 ', 'Burin des Rozier Donatien', 'myname.std7@edu.hefr.ch', 'myname7.std', 'Etudiant', 'Informatique'),
    ('Std8 ', 'Castella Thomas', 'myname.std8@edu.hefr.ch', 'myname8.std', 'Etudiant', 'Informatique'),
    ('Std9 ', 'Diaconsecu Stefan', 'myname.std9@edu.hefr.ch', 'myname9.std', 'Etudiant', 'Informatique'),
    ('Std10', 'Doudin Yann', 'myname.std0@edu.hefr.ch', 'myname0.std', 'Etudiant', 'Informatique'),
    ('Std11', 'Dumas Ayrton', 'myname.std1@edu.hefr.ch', 'myname1.std', 'Etudiant', 'Informatique'),
    ('Std12', 'Favre Alexandre', 'myname.std2@edu.hefr.ch', 'myname2.std', 'Etudiant', 'Informatique'),
    ('Std13', 'Firat Cemali', 'myname.std3@edu.hefr.ch', 'myname3.std', 'Etudiant', 'Informatique'),
    ('Std14', 'Fragnière Sébastien', 'myname.std4@edu.hefr.ch', 'myname4.std', 'Etudiant', 'Informatique'),
    ('Std15', 'Gauthier Abel', 'myname.std5@edu.hefr.ch', 'myname5.std', 'Etudiant', 'Informatique'),
    ('Std16', 'Genillou Maxime', 'myname.std6@edu.hefr.ch', 'myname6.std', 'Etudiant', 'Informatique'),
    ('Std17', 'Horner Frédéric', 'myname.std7@edu.hefr.ch', 'myname7.std', 'Etudiant', 'Informatique'),
    ('Std18', 'Ly Stéphane', 'myname.std8@edu.hefr.ch', 'myname8.std', 'Etudiant', 'Informatique'),
    ('Std19', 'Macor Adriano', 'myname.std9@edu.hefr.ch', 'myname9.std', 'Etudiant', 'Informatique'),
    ('Std20', 'Miche Philippe', 'myname.std0@edu.hefr.ch', 'myname0.std', 'Etudiant', 'Informatique'),
    ('Std21', 'Moraïtinis Anick', 'myname.std1@edu.hefr.ch', 'myname1.std', 'Etudiant', 'Informatique'),
    ('Std22', 'Morattel Damien', 'myname.std2@edu.hefr.ch', 'myname2.std', 'Etudiant', 'Informatique'),
    ('Std23', 'Müller Dylan', 'myname.std3@edu.hefr.ch', 'myname3.std', 'Etudiant', 'Informatique'),
    ('Std24', 'Paccard Samuel', 'myname.std4@edu.hefr.ch', 'myname4.std', 'Etudiant', 'Informatique'),
    ('Std25', 'Pasquier Vincent', 'myname.std5@edu.hefr.ch', 'myname5.std', 'Etudiant', 'Informatique'),
    ('Std26', 'Pauchard Lucas', 'myname.std6@edu.hefr.ch', 'myname6.std', 'Etudiant', 'Informatique'),
    ('Std27', 'Peña López Nestor', 'myname.std7@edu.hefr.ch', 'myname7.std', 'Etudiant', 'Informatique'),
    ('Std28', 'Perdrizat Bryan', 'myname.std8@edu.hefr.ch', 'myname8.std', 'Etudiant', 'Informatique'),
    ('Std29', 'Pharisa Valentin', 'myname.std9@edu.hefr.ch', 'myname9.std', 'Etudiant', 'Informatique'),
    ('Std30', 'Porteli Jeremy', 'myname.std0@edu.hefr.ch', 'myname0.std', 'Etudiant', 'Informatique'),
    ('Std31', 'Previte Davide', 'myname.std1@edu.hefr.ch', 'myname1.std', 'Etudiant', 'Informatique'),
    ('Std32', 'Pythoud Kilian', 'myname.std2@edu.hefr.ch', 'myname2.std', 'Etudiant', 'Informatique'),
    ('Std33', 'Ruffray Benoit', 'myname.std3@edu.hefr.ch', 'myname3.std', 'Etudiant', 'Informatique'),
    ('Std34', 'Sauty Axel', 'myname.std4@edu.hefr.ch', 'myname4.std', 'Etudiant', 'Informatique'),
    ('Std35', 'Schaller Alain', 'myname.std5@edu.hefr.ch', 'myname5.std', 'Etudiant', 'Informatique'),
    ('Std36', 'Siggen Yvan', 'myname.std6@edu.hefr.ch', 'myname6.std', 'Etudiant', 'Informatique'),
    ('Std37', 'Tille Josué', 'myname.std7@edu.hefr.ch', 'myname7.std', 'Etudiant', 'Informatique'),
    ('Std38', 'Torche  Samuel', 'myname.std8@edu.hefr.ch', 'myname8.std', 'Etudiant', 'Informatique'),
    ('Std39', 'Tschopp Bruno', 'myname.std9@edu.hefr.ch', 'myname9.std', 'Etudiant', 'Informatique'),
    ('Std40', 'Vallat Matthieu', 'myname.std0@edu.hefr.ch', 'myname0.std', 'Etudiant', 'Informatique'),
    ('Std41', 'Waeber Gilles', 'myname.std1@edu.hefr.ch', 'myname1.std', 'Etudiant', 'Informatique'),
    ('Std42', 'Yerly Dylan', 'myname.std2@edu.hefr.ch', 'myname2.std', 'Etudiant', 'Informatique'),
    ('Std43', 'Zambon Yannick', 'myname.std3@edu.hefr.ch', 'myname3.std', 'Etudiant', 'Informatique');

INSERT INTO Type
    (Name, CreditECTS)
VALUES
    ('PS4', 4.5),
    ('PS5', 5),
    ('PS6', 6),
    ('Bachelor', 12);

INSERT INTO Project
    (Title, State, Year, UserID_Owner, TypeName, NbrMaxStudent)
VALUES
    ('Adaptation de POP-Java aux versions récentes de Java', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Advanced Interface for Technogym Equipment', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Analyse d images prises par des pièges photographiques', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Analytics and visualisation tools for point of sales and stock management', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Annotation rapide de données pour du machine learning', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Application mobile intégrant un chatbot pour La Liberté', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Application pour gestion d un parc de véhicules', 'Concours', 2019, 1, 'Bachelor', 2),
    ('Apprendre la préhistoire européenne grâce à l ADN ancien', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Assistance Mobile Application', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Automatisation d analyses génétiques', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Bird Voice Recognition with Neural Networks', 'Concours', 2019, 1, 'Bachelor', 1),
    ('ChimSPA: SPA pour site personnel de professeurs en Chimie', 'Concours', 2019, 1, 'Bachelor', 1),
    ('cityUnity: visualisation of city environment using Unity and accurate swisstopo maps', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Communication Protocol for the IoT', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Comparaison de protéines et d ADN par la méthode du diagramme diagonal', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Control platform for the INNOSUISSE Project: "smart home with thermal Storage"', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Création d une application pour augmenter l attention des conducteurs des futures voitures semi', 'Concours', 2019, 1, 'Bachelor', 1),
    ('DESPRI: Demand Estimation and Pricing with Machine Learning', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Détecter l Etat Emotionnel en temps Réel des Utilisateurs avec le Casque Emotiv', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Dévélopement d une plateform web pour généticiens', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Edge Cloud Orchestration and monitoring', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Event Manager - Exploration', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Fonctions de gestion d un système pour monitoring de matériel pour aide humanitaire', 'Concours', 2019, 1, 'Bachelor', 1),
    ('From sights to insights with intelligent brills - Florida Atlantic University', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Géolocalisation dans le milieu urbain', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Gestion du trafic en ville de Fribourg', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Geston de certificats de travail', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Glove-Based Cued Speech Recognition', 'Concours', 2019, 1, 'Bachelor', 1),
    ('HandiControl2: IA à la découverte d une certaine autonomie pour les polyhandicappés', 'Concours', 2019, 1, 'Bachelor', 1),
    ('I/O Link Spy for the IoT', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Improving MitMProxy for HTTP/2', 'Concours', 2019, 1, 'Bachelor', 1),
    ('IMS-VoIP PBX Gateway', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Intelligence Artificielle pour reconnaître le temps qu il fait à partir d une image', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Jailbreak iOS 12 on iPhone X', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Les possibilités insoupçonnées de nos labos : Un émulateur de réseau et un générateur de trafic', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Long Range Bluetooth 5 pour Hydrocontest 2019', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Machine Learning for Signature Verification on Samsung Galaxy Note', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Mal de tête aux urgences : logiciel pour détecter une hémorragie cérébrale', 'Concours', 2019, 1, 'Bachelor', 1),
    ('MeccanoLego Sharing Platform', 'Concours', 2019, 1, 'Bachelor', 1),
    ('MeccanoLego v2.1', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Medical Machine Learning', 'Concours', 2019, 1, 'Bachelor', 1),
    ('MediCom1 : Messagerie instantanée et sécurisée pour les professionnels de la santé', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Nouveau langage de programmation pour le robot Thymio II', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Orchestration of a two slices Telco Cloud', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Outil de gestion des projets d étudiants', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Outil de planification d itinéraires pour deux roues', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Play with my friends', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Redondance ethernet avec HSR-PRP et tests dans une infrastructure réelle', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Simulation de véhicules autonomes avec la plateforme Apollo', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Smart Building on the Move', 'Concours', 2019, 1, 'Bachelor', 1),
    ('SmartNurse iv', 'Concours', 2019, 1, 'Bachelor', 1),
    ('SmartNurse v', 'Concours', 2019, 1, 'Bachelor', 1),
    ('SmartReactor - système d alarme pour réacteur chimique', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Supply Chain Management with Blockchain', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Système de recommandation intelligent pour une application de réalité augmentée', 'Concours', 2019, 1, 'Bachelor', 1),
    ('The Ultimate Pilot Log Book', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Totem interactif Renault', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Traitement du cancer : Automatisation d analyses de protéines', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Une technologie meilleure que la fibre optique à l HEIA-FR: FSO second part', 'Concours', 2019, 1, 'Bachelor', 1),
    ('VehiSi: Vehicle signatures from roadside WiFi monitoring', 'Concours', 2019, 1, 'Bachelor', 1),
    ('Virtual Switch programming through P4', 'Concours', 2019, 1, 'Bachelor', 1),
    ('VR into art', 'Concours', 2019, 1, 'Bachelor', 1);
    
    


INSERT INTO Affiliated
    (ProjectID, SectionName)
VALUES
    (1, 'Informatique'),
    (2, 'Informatique'),
    (3, 'Informatique'),
    (4, 'Informatique'),
    (5, 'Informatique'),
    (6, 'Informatique'),
    (7, 'Informatique'),
    (8, 'Informatique'),
    (9, 'Informatique'),
    (10, 'Informatique'),
    (11, 'Informatique'),
    (12, 'Informatique'),
    (13, 'Informatique'),
    (14, 'Informatique'),
    (15, 'Informatique'),
    (16, 'Informatique'),
    (17, 'Informatique'),
    (18, 'Informatique'),
    (19, 'Informatique'),
    (20, 'Informatique'),
    (21, 'Informatique'),
    (22, 'Informatique'),
    (23, 'Informatique'),
    (24, 'Informatique'),
    (25, 'Informatique'),
    (26, 'Informatique'),
    (27, 'Informatique'),
    (28, 'Informatique'),
    (29, 'Informatique'),
    (30, 'Informatique'),
    (31, 'Informatique'),
    (32, 'Informatique'),
    (33, 'Informatique'),
    (34, 'Informatique'),
    (35, 'Informatique'),
    (36, 'Informatique'),
    (37, 'Informatique'),
    (38, 'Informatique'),
    (39, 'Informatique'),
    (40, 'Informatique'),
    (41, 'Informatique'),
    (42, 'Informatique'),
    (43, 'Informatique'),
    (44, 'Informatique'),
    (45, 'Informatique'),
    (46, 'Informatique'),
    (47, 'Informatique'),
    (48, 'Informatique'),
    (49, 'Informatique'),
    (50, 'Informatique'),
    (51, 'Informatique'),
    (52, 'Informatique'),
    (53, 'Informatique'),
    (54, 'Informatique'),
    (55, 'Informatique'),
    (56, 'Informatique'),
    (57, 'Informatique'),
    (58, 'Informatique'),
    (59, 'Informatique'),
    (60, 'Informatique'),
    (61, 'Informatique'),
    (62, 'Informatique');


INSERT INTO Choices
    (ProjectID, UserID, Weight)
VALUES
    (61, 2, 1),
    (32, 2, 2),
    (21, 2, 3),
    (2, 4, 1),
    (16, 4, 2),
    (17, 4, 1),
    (19, 4, 2),
    (41, 4, 3),
    (10, 5, 1),
    (19, 5, 1),
    (6, 5, 1),
    (3, 5, 1),
    (37, 5, 2),
    (33, 5, 3),
    (21, 6, 1),
    (59, 6, 1),
    (32, 6, 2),
    (36, 6, 3),
    (26, 6, 4),
    (33, 7, 1),
    (28, 7, 2),
    (47, 7, 3),
    (1, 8, 1),
    (23, 8, 1),
    (12, 8, 2),
    (19, 8, 3),
    (32, 9, 1),
    (35, 9, 2),
    (59, 9, 3),
    (11, 10, 1),
    (7, 10, 2),
    (27, 10, 3),
    (38, 12, 1),
    (18, 12, 2),
    (19, 12, 3),
    (19, 13, 1),
    (47, 13, 2),
    (22, 13, 3),
    (19, 14, 1),
    (35, 14, 2),
    (27, 14, 3),
    (40, 15, 1),
    (19, 15, 2),
    (39, 15, 3),
    (19, 16, 1),
    (40, 16, 1),
    (28, 16, 2),
    (14, 16, 3),
    (45, 17, 1),
    (56, 17, 2),
    (2, 17, 3),
    (22, 18, 1),
    (12, 18, 2),
    (16, 18, 3),
    (19, 19, 1),
    (21, 19, 2),
    (35, 19, 3),
    (41, 20, 1),
    (31, 20, 1),
    (32, 20, 1),
    (61, 20, 2),
    (21, 20, 3),
    (45, 22, 1),
    (35, 22, 1),
    (1, 22, 2),
    (19, 22, 3),
    (9, 23, 1),
    (7, 23, 2),
    (45, 23, 3),
    (9, 24, 1),
    (14, 24, 1),
    (22, 24, 1),
    (32, 24, 1),
    (19, 24, 2),
    (25, 24, 2),
    (16, 24, 2),
    (35, 24, 3),
    (21, 24, 3),
    (32, 25, 1),
    (41, 25, 1),
    (21, 25, 2),
    (35, 25, 2),
    (61, 25, 3),
    (8, 26, 1),
    (35, 26, 2),
    (30, 26, 3),
    (20, 27, 1),
    (4, 27, 2),
    (8, 27, 3),
    (45, 28, 1),
    (20, 28, 2),
    (9, 28, 2),
    (12, 28, 3),
    (14, 29, 1),
    (43, 29, 2),
    (38, 29, 3),
    (32, 30, 1),
    (35, 30, 2),
    (19, 30, 2),
    (12, 30, 3),
    (19, 31, 1),
    (4, 31, 2),
    (47, 31, 3),
    (14, 32, 1),
    (30, 32, 2),
    (43, 32, 3),
    (58, 33, 1),
    (52, 33, 2),
    (51, 33, 3),
    (5, 34, 1),
    (28, 34, 2),
    (33, 34, 2),
    (3, 34, 3),
    (20, 35, 1),
    (16, 35, 2),
    (4, 35, 3),
    (18, 36, 4),
    (27, 38, 1),
    (61, 38, 2),
    (31, 38, 3),
    (12, 39, 1),
    (4, 39, 2),
    (22, 39, 2),
    (2, 39, 3),
    (53, 39, 4),
    (19, 40, 1),
    (38, 40, 2),
    (16, 40, 3),
    (29, 40, 4),
    (46, 41, 1),
    (38, 41, 2),
    (2, 41, 3),
    (33, 42, 1),
    (9, 42, 2),
    (11, 42, 3),
    (37, 42, 3),
    (8, 43, 1),
    (3, 43, 2),
    (58, 43, 3),
    (35, 44, 1),
    (21, 44, 2),
    (61, 44, 3);
    